import { number, progress, distance, formatDistance, calories, activeMinutes, pace, formatDate } from './calculations.js';
import { series, summarize, streaks } from './statistics.js';
import { definitions } from './achievements.js';
import { dateKey } from './storage.js';
const $ = id => document.getElementById(id);
export const el = $;
export function renderHome(state) {
  const today = dateKey(); const day = state.days[today]; const pct = progress(day.steps, day.goal);
  $('step-count').textContent = number(day.steps); $('goal-value').textContent = number(state.profile.goal); $('goal-ring').style.setProperty('--progress', `${pct * 3.6}deg`); $('goal-ring').setAttribute('aria-label', `${number(day.steps)} of ${number(day.goal)} steps`);
  $('distance-value').textContent = formatDistance(distance(day.steps, state.profile.stride, state.profile.unit), state.profile.unit); $('calories-value').textContent = `${number(calories(day.steps, state.profile.weight))} kcal`; $('active-value').textContent = `${activeMinutes(day.activeSeconds)} min`; $('pace-value').textContent = pace(day.steps, day.activeSeconds); $('goal-message').textContent = pct >= 100 ? 'Goal complete — amazing!' : `${number(Math.max(0, day.goal - day.steps))} steps to go`;
  $('today-label').textContent = formatDate(today, { weekday: 'long', month: 'short', day: 'numeric' }); const hour = new Date().getHours(); $('greeting').textContent = hour < 12 ? 'GOOD MORNING' : hour < 18 ? 'GOOD AFTERNOON' : 'GOOD EVENING'; $('pause-button').innerHTML = !state.settings.motionEnabled ? '▶&nbsp; Start tracking' : day.paused ? '▶&nbsp; Resume tracking' : 'Ⅱ&nbsp; Pause tracking'; $('developer-tools').classList.toggle('hidden', !state.settings.developerMode);
}
export function renderHistory(state) {
  const body = $('history-body'); const entries = Object.entries(state.days).sort((a, b) => b[0].localeCompare(a[0])).slice(0, 60); body.innerHTML = entries.map(([key, day]) => `<tr><td><strong>${formatDate(key)}</strong><small>${key === dateKey() ? 'Today' : ''}</small></td><td>${number(day.steps)}</td><td>${number(day.goal)}</td><td>${formatDistance(distance(day.steps, state.profile.stride, state.profile.unit), state.profile.unit)}</td><td><span class="table-status ${day.steps >= day.goal ? 'complete' : ''}">${day.steps >= day.goal ? 'Complete' : 'In progress'}</span></td></tr>`).join(''); $('empty-history').classList.toggle('hidden', entries.length > 0); $('history-summary').textContent = `${entries.filter(([, day]) => day.steps >= day.goal).length} goals completed`;
}
export function renderStats(state, days = 7) {
  const items = series(state, days); const summary = summarize(items); const totalDistance = items.reduce((sum, item) => sum + distance(item.steps, state.profile.stride, state.profile.unit), 0); const totalCalories = items.reduce((sum, item) => sum + calories(item.steps, state.profile.weight), 0); const totalActive = items.reduce((sum, item) => sum + Number(item.activeSeconds || 0), 0);
  $('average-steps').textContent = number(summary.average); $('average-caption').textContent = `Last ${days} days`; $('best-day').textContent = summary.best ? number(summary.best.steps) : '—'; $('best-day-caption').textContent = summary.best ? formatDate(summary.best.key) : 'Keep going'; $('completion-rate').textContent = `${summary.completion}%`; $('completion-caption').textContent = `Last ${days} days`; $('total-distance').textContent = formatDistance(totalDistance, state.profile.unit); $('total-calories').textContent = `${number(totalCalories)} kcal`; $('total-active').textContent = `${activeMinutes(totalActive)} min`; drawChart(items, state.profile.goal); $('insight-text').textContent = summary.average >= state.profile.goal ? 'You are averaging above your daily goal. Keep that momentum!' : `You are ${number(Math.max(0, state.profile.goal - summary.average))} steps from your daily average goal.`;
}
function drawChart(items, goal) {
  const canvas = $('steps-chart'); const dpr = window.devicePixelRatio || 1; const width = canvas.clientWidth || 600; const height = 240; canvas.width = width * dpr; canvas.height = height * dpr; const ctx = canvas.getContext('2d'); ctx.scale(dpr, dpr); const max = Math.max(goal, ...items.map(item => item.steps), 1); const pad = { top: 18, right: 14, bottom: 30, left: 42 }; const x = index => pad.left + (index * (width - pad.left - pad.right)) / Math.max(1, items.length - 1); const y = value => height - pad.bottom - (value / max) * (height - pad.top - pad.bottom); ctx.strokeStyle = getComputedStyle(document.body).getPropertyValue('--border'); ctx.fillStyle = getComputedStyle(document.body).getPropertyValue('--muted'); ctx.font = '11px system-ui'; [0, .5, 1].forEach(t => { ctx.beginPath(); ctx.moveTo(pad.left, y(max * t)); ctx.lineTo(width - pad.right, y(max * t)); ctx.stroke(); ctx.fillText(number(max * t), 4, y(max * t) + 4); }); ctx.strokeStyle = '#f59e0b'; ctx.setLineDash([5, 5]); ctx.beginPath(); ctx.moveTo(pad.left, y(goal)); ctx.lineTo(width - pad.right, y(goal)); ctx.stroke(); ctx.setLineDash([]); ctx.strokeStyle = '#0f766e'; ctx.lineWidth = 3; ctx.beginPath(); items.forEach((item, index) => index ? ctx.lineTo(x(index), y(item.steps)) : ctx.moveTo(x(index), y(item.steps))); ctx.stroke(); items.forEach((item, index) => { ctx.fillStyle = '#0f766e'; ctx.beginPath(); ctx.arc(x(index), y(item.steps), 4, 0, Math.PI * 2); ctx.fill(); if (items.length <= 14 || index % Math.ceil(items.length / 7) === 0) { ctx.fillStyle = getComputedStyle(document.body).getPropertyValue('--muted'); ctx.fillText(item.key.slice(5), x(index) - 12, height - 8); } });
}
export function renderAchievements(state) { const unlocked = Object.keys(state.achievements).length; const s = streaks(state); $('achievement-count').textContent = `${unlocked} unlocked`; $('current-streak').textContent = `${s.current} day streak`; $('best-streak').textContent = `${s.best} days`; $('achievements-grid').innerHTML = definitions.map(item => { const done = Boolean(state.achievements[item.id]); return `<article class="achievement ${done ? 'unlocked' : ''}"><span class="achievement-icon">${item.icon}</span><div><h3>${item.title}</h3><p>${item.text}</p>${done ? `<small>Unlocked ${formatDate(state.achievements[item.id].slice(0, 10))}</small>` : '<small>Locked</small>'}</div></article>`; }).join(''); }
export function populateSettings(state) { $('profile-name').value = state.profile.name; $('profile-age').value = state.profile.age; $('profile-height').value = state.profile.height; $('profile-weight').value = state.profile.weight; $('profile-goal').value = state.profile.goal; $('profile-stride').value = state.profile.stride; $('profile-unit').value = state.profile.unit; $('dark-theme').checked = state.profile.theme === 'dark'; $('motion-enabled').checked = state.settings.motionEnabled; $('developer-mode').checked = state.settings.developerMode; document.documentElement.dataset.theme = state.profile.theme; }
export function toast(message, kind = '') { const node = $('toast'); node.textContent = message; node.className = `toast show ${kind}`; window.clearTimeout(toast.timer); toast.timer = window.setTimeout(() => node.classList.remove('show'), 2800); }
export function showView(name) { document.querySelectorAll('.view').forEach(view => view.classList.toggle('hidden', view.dataset.view !== name)); document.querySelectorAll('[data-nav]').forEach(nav => nav.classList.toggle('active', nav.dataset.nav === name)); $('app').focus({ preventScroll: true }); }
